version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cep-postgres
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: incident_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    
  prometheus:
    image: prom/prometheus:latest
    container_name: cep-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway" # Truque essencial para funcionar no Linux/Ubuntu!
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: cep-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Senha padrão simples para testes
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - ./cep_engine.log:/var/log/cep_engine.log
      - ./monitoring/promtail.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

volumes:
  grafana_data:
